pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo "build the application" '
            }
        }
        stage('Test') {
            steps {
                sh 'echo "test the application "'
            }
        stage('Deploy') {
            steps {
                sh 'echo "Deploy the application" '
            }
        }

            post {
                always {
                    echo 'this will always run'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
